name: ci
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    timeout-minutes: 60
    strategy:
      matrix:
        include:
          - java: 17
          - java: 25
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v5
      with:
        java-version: ${{matrix.java}}
        distribution: adopt
    - uses: actions/checkout@v6
    - uses: coursier/cache-action@v8
    - uses: sbt/setup-sbt@v1
    - shell: bash
      run: sbt -v
           --server
           -J-Xmx6G
           scalafmtSbtCheck
           scalafmtCheckAll
           test
